cookie:
  expiry_days: 30
  key: some_signature_key # Must be a string
  name: some_cookie_name
credentials:
  usernames:
    iaxxon:
      email: francisco@iaxxon.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Francisco
      last_name: IAXXON
      logged_in: False # Will be managed automatically
      password: ADM_sos*24 # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Rebecca
      last_name: Briggs
      logged_in: False # Will be managed automatically
      password: def # Will be hashed automatically
      roles: # Optional
      - viewer
